version: '3.4'

networks:
 tibberrobotnetwork:

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
     - ACCEPT_EULA=Y
     - SA_PASSWORD=Bscs14f018
    ports:
      - "1433:1433"
    networks:
     - tibberrobotnetwork
  web:
    image: ${DOCKER_REGISTRY-}web
    build:
      context: .
      dockerfile: Web/Dockerfile
    ports:
      - "5001:8081" 
    depends_on:
    - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
     - tibberrobotnetwork
    restart: on-failure